src_files = [
	'codon.cpp', 
	'TripletBase.cpp'
]

env = Environment(TARGET_ARCH = 'x86')
if env['PLATFORM'] == 'win32':
	env.Append(LIBPATH=['C:\\Users\\tolkjen\\Documents\\boost_1_53_0\\lib\\shared_all', 'C:\\Python27\\libs'])
	env.Append(CPPPATH=['C:\\Users\\tolkjen\\Documents\\boost_1_53_0', 'C:\\Python27\\include'])
	env.Append(CCFLAGS=['/MD'])
else:
	env.ParseConfig('pkg-config --cflags python')
	env.Append(LIBS=['boost_python'])
	env.Append(LINKFLAGS=['-fPIC'])

env.SharedLibrary(target='codon', source=src_files)
