libraries = ['boost_python']
library_dirs = ['/usr/lib64']
linker_flags = ['-fPIC']
include_dirs = ['/usr/include/python2.7', '/usr/include']
src_files = ['codon.cpp', 'TripletBase.cpp']
SharedLibrary(target='codon', source=src_files, LIBS=libraries, LIBPATH=library_dirs, CPPPATH=include_dirs, LINKFLAGS=linker_flags)
