import platform

# Set environment variables according to OS platform
env = Environment(TARGET_ARCH = 'x86')
if platform.system() == "Windows":
	env.Append(LIBPATH = [
		'C:\\Users\\tolkjen\\Documents\\boost_1_53_0\\lib\\shared_all', 
		'C:\\Users\\tolkjen\\Documents\\boost_1_53_0\\stage\\lib', 
		'C:\\Python27\\libs'
	])
	env.Append(CPPPATH = [
		'C:\\Users\\tolkjen\\Documents\\boost_1_53_0', 
		'C:\\Python27\\include'
	])
	env.Append(CPPPATH = ['#libclassifier/src', '#libclassifier/src/lib'])
	env.Append(CCFLAGS = ['/MD', '/EHsc'])
else:
	env.Append(CPPPATH = ['#libclassifier/src', '#libclassifier/src/lib'])
	env.ParseConfig('pkg-config --cflags --libs python')
	env.Append(LIBS=['boost_python', 'boost_system'])
	env.Append(LINKFLAGS=['-fPIC'])
	env.Append(CCFLAGS=['-std=c++11'])

# Add more SConscripts
shared_lib = SConscript('src/lib/SConscript', 
	exports = ['env'], 
	variant_dir = 'bin/lib',
	duplicate = 0)

# Aliases
Alias('lib', shared_lib)
binaries = Alias('all', [shared_lib])

# Cleanup
Clean(shared_lib, 'bin/lib')
Clean(binaries, 'bin')

Return('shared_lib')
