import platform

Import('*')

source = Glob('*.cpp')

# Build shared library
shared_lib_bin = env.SharedLibrary('classifier', source)

if platform.system() == "Windows":
	# Copy library to unittests directory
	shared_lib_tests = Command('../../unittests/classifier.pyd', shared_lib_bin, Copy("$TARGET", "$SOURCE"))

	# Copy shared library to Django directory
	shared_lib = Command('#Django/med/utility/classifier.pyd', shared_lib_bin, Copy("$TARGET", "$SOURCE"))

	# Copy Dll and set as a dependency
	dll = Command(
		'#Django/med/utility/boost_python-vc110-mt-1_53.dll', 
		'#libclassifier/import/boost_python-vc110-mt-1_53.dll', 
		Copy("$TARGET", "$SOURCE")
	)
	Depends(shared_lib, dll)
else:
	# Copy library to unittests directory
	shared_lib_tests = Command('../../unittests/classifier.so', shared_lib_bin, Copy("$TARGET", "$SOURCE"))

	# Copy shared library to Django directory
	shared_lib = Command('#Django/med/utility/classifier.so', shared_lib_bin, Copy("$TARGET", "$SOURCE"))

# Common dependencies
Depends(shared_lib, shared_lib_bin)
Depends(shared_lib, shared_lib_tests)

Return('shared_lib')
